[MM-241] Corregir errores detectados por lgtm
ong-bitcoin-argentina/DIDI-SSI-Issuer-module-frontend pull request #6
Opened 2021-10-22 14:00 UTC by fedelmar

-Se corrige el código en base a advertencias de lgtm

2021-10-26 14:57 UTC, MatiasOS requested changes
Hay unos detalles que se repiten en todos los cambios. Hay que revisarlos

2021-10-26 14:57 UTC, MatiasOS commented on src/app/administrative/list/Delegates.js
> +		const error = this.props.error;
Acá por qué sacaste **this.state.error**? Tendríamos que dejarlo para no cambiar el comportamiento

2021-10-26 14:57 UTC, MatiasOS commented on src/app/certificates/edit/Certificate.js
> +			self.setState(prevState => ({
El segundo **setState** no hace falta. Se puede mover el **error: undefined** al primer **setState**.

2021-10-26 14:57 UTC, MatiasOS commented on src/app/certificates/edit/Certificate.js
> +				self.setState(prevState => ({
Acá en la línea 502 hace:
`const partToUpdate = self.state.cert.data.participant[position]`
después en la 505, 
`if (didDataToUpdate) didDataToUpdate.value = participant.did;`

Hay que pisar **self.state.cert.data.participant[position].value** usando  destructirung

2021-10-26 14:57 UTC, MatiasOS commented on src/app/certificates/edit/Certificate.js
> +		this.setState(prevState => ({ cert: prevState.cert }));
Acá en  la 441, hace
**const partData = this.state.cert.data.participant[0];**
o en la 444
**this.state.cert.data.participant.splice(index, 1)**

Hay que ver como hacer para hacerlo sin manipular el estado directamente

2021-10-26 14:57 UTC, MatiasOS commented on src/app/certificates/list/Certificates.js
> +		const error = this.props.error;
Acá también por qué sacaste **this.state.error**?

2021-10-26 14:57 UTC, MatiasOS commented on src/app/main/Main.js
> +		self.setState(prevState => ({
En la línea 289,  **const cert = self.state.certificates.find(t => t._id === id);** y luego de agrega **actions** y **select**

Eso es lo que hay que pisar el **setState**

2021-10-26 14:57 UTC, MatiasOS commented on src/app/main/Main.js
> +			selectedCerts: selectedCerts
Acá está medio raro. en la 381 hace *let allSelected = true;* y en la 386  **allSelected = false;** . No me queda claro por que se lo sacaste al setState

2021-10-26 14:57 UTC, MatiasOS commented on src/app/main/Main.js
> +		this.setState(prevState => ({
En la 463, hace
const certs = this.state.certificates.filter(t => toEmmit.indexOf(t._id) > -1);

y en la 464, dentro del forEach lo modifica.

2021-10-26 14:57 UTC, MatiasOS commented on src/app/main/Main.js
> +		self.setState(prevState => ({
Ver este **setState** también

2021-10-26 14:57 UTC, MatiasOS commented on src/app/templates/edit/Template.js
> +		this.setState(prevState => ({
Acá le hace un push en la línea de arriba, hacelo como **[...this.state.template.data[type], data]**

2021-10-26 14:57 UTC, MatiasOS commented on src/app/templates/edit/Template.js
> +			this.setState(prevState => ({
Revisar este setState

2021-10-26 14:57 UTC, MatiasOS commented on src/app/templates/edit/Template.js
> +			this.setState(prevState => ({
Revisar este **setState**

2021-10-26 14:57 UTC, MatiasOS commented on src/app/templates/edit/Template.js
> +			template: {
No te olvides el destructuring

2021-10-26 14:57 UTC, MatiasOS commented on src/app/utils/dialogs/QrDialog.js
> +						self.setState({ loading: false });
Acá por qué le sacaste el error?

2021-10-26 14:57 UTC, MatiasOS commented on src/app/utils/dialogs/QrDialog.js
> +			console.log(error)
Este se te paso?

2021-10-26 14:57 UTC, MatiasOS commented on src/app/utils/dialogs/QrDialog.js
> +				self.setState({ loading: false });
Acá tambien sacaste el error

2021-10-26 14:57 UTC, MatiasOS commented on src/app/utils/dialogs/TemplateFieldAddDialog.js
> +							this.setState(prevState => ({
En la línea anterior le hace un push al array en this.state.options. Hay que hacer copiando el array con **[...this.state.options, this.state.option]**

2021-10-26 14:57 UTC, MatiasOS commented on src/app/utils/dialogs/TemplateFieldAddDialog.js
> +									this.setState(prevState => ({
La línea anterior es **this.state.options.splice(key, 1);** hay que usar eso en el setState

2021-10-26 15:00 UTC, fedelmar commented on src/app/administrative/list/Delegates.js
> +		const error = this.props.error;
porq lo lee, pero nunca se carga en el state la variable error

2021-10-26 15:01 UTC, fedelmar commented on src/app/certificates/list/Certificates.js
> +		const error = this.props.error;
lo mismo que arriba, no esta definido pero aun asi lo lee

2021-10-26 15:01 UTC, fedelmar commented on src/app/utils/dialogs/QrDialog.js
> +						self.setState({ loading: false });
porq se guarda en el state, pero luego no se lee

2021-10-26 15:24 UTC, fedelmar commented on src/app/administrative/list/Delegates.js
> +		const error = this.props.error;
![image](https://user-images.githubusercontent.com/63212238/138910607-9ebae5ee-f7d7-47ef-8948-c2a3bfde1df2.png)

2021-10-28 13:20 UTC, MatiasOS requested changes

2021-10-28 13:20 UTC, MatiasOS commented on src/app/certificates/edit/Certificate.js
> +					data: {
No te olvides el destructuring en cada nivel

2021-10-29 17:22 UTC, MatiasOS requested changes

2021-10-29 17:22 UTC, MatiasOS commented on src/app/main/Main.js
> +		this.setState(prevState => ({
Este quedó mal aún.

2021-10-29 18:17 UTC, MatiasOS approved these changes

2021-10-29 18:18 UTC, merged